name: Schema Validation

on: [push, pull_request]

jobs:
  test:

    runs-on: {{ '${{ matrix.os }}' }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
    env:
      PYVER: {{ '${{ matrix.python-version }}' }}
      CI_OS: {{ '${{ matrix.os }}' }}

    steps:
    - uses: actions/checkout@v1

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Create environment for package
      shell: bash
      run: |
        . repo_management/github-actions/initialize_conda.sh
        conda activate
        conda info
        conda create -n schema python==$PYVER pyyaml pydantic

    - name: Run Schema Validation
      shell: bash
      run: |
        . devtools/github-actions/initialize_conda.sh
        conda activate schema
        cd schema
        python validation.py
